export const USER_INFO = 'USER_INFO'

export const LOAD_COUNTRIES = 'LOAD_COUNTRIES'
export const LOAD_USER_DATA = 'LOAD_USER_DATA'

export const ADD_USER_ID = 'ADD_USER_ID'
export const ADD_LEARNED_COUNTRY = 'ADD_LEARNED_COUNTRY'
export const REMOVE_LEARNED_COUNTRY = 'REMOVE_LEARNED_COUNTRY'

export const REQUEST = '_REQUEST'
export const SUCCESS = '_SUCCESS'
export const FAILURE = '_FAILURE'
